app:
  name: 'users-graphql'
  host: 'http://localhost'
  port: 5000

arangodb:
  urls:
    - 'http://localhost:8529'
  name: 'farmaco_test'
  username: 'farmaco_test'
  password: 'secret'
  certs: []

graphql:
  introspection: true
  playground: true
  subscriptions: false
  autoSchemaFile: true
  sortSchema: true
