export const SCOPES_ACTIONS_NODES = [
  'SEARCH',
  'COUNT',
  'FIND',
  'CREATE',
  'UPDATE',
  'DELETE',
];

export const SCOPES_ACTIONS_EDGES = ['ADD', 'CHANGE', 'REMOVE', 'READ'];

export const SCOPES_ACTIONS = {
  2: SCOPES_ACTIONS_NODES,
  3: SCOPES_ACTIONS_EDGES,
};
