export enum PermissionsEnum {
  usersCreate = 'users_create',
  usersUpdate = 'users_update',
  usersDelete = 'users_delete',
  usersFind = 'users_find',
  usersSearch = 'users_search',
  usersCount = 'users_count',

  usersHasRoleAdd = 'usershasrole_add',
  usersHasRoleChange = 'usershasrole_change',
  usersHasRoleRemove = 'usershasrole_remove',
  usersHasRoleRead = 'usershasrole_read',

  rolesCreate = 'roles_create',
  rolesUpdate = 'roles_update',
  rolesDelete = 'roles_delete',
  rolesFind = 'roles_find',
  rolesSearch = 'roles_search',
  rolesCount = 'roles_count',

  rolesHasScopeAdd = 'roleshasscope_add',
  rolesHasScopeChange = 'roleshasscope_change',
  rolesHasScopeRemove = 'roleshasscope_remove',
  rolesHasScopeRead = 'roleshasscope_read',

  scopesCreateOne = 'scopes_create_one',
  scopesCreateAll = 'scopes_create_all',
  scopesUpdateOne = 'scopes_update_one',
  scopesUpdateAll = 'scopes_update_all',
  scopesDeleteOne = 'scopes_delete_one',
  scopesDeleteAll = 'scopes_delete_all',
  scopesFind = 'scopes_find',
  scopesSearch = 'scopes_search',
  scopesCount = 'scopes_count',
}
